//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdwardsApp1.DocObj25ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfoShareFault", Namespace="http://sdl.com/trisoft/2012/06/WebServices/Contracts/Faults/API25/")]
    [System.SerializableAttribute()]
    public partial class InfoShareFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long InfoShareErrorNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OriginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XMLDetailField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long InfoShareErrorNumber {
            get {
                return this.InfoShareErrorNumberField;
            }
            set {
                if ((this.InfoShareErrorNumberField.Equals(value) != true)) {
                    this.InfoShareErrorNumberField = value;
                    this.RaisePropertyChanged("InfoShareErrorNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Origin {
            get {
                return this.OriginField;
            }
            set {
                if ((object.ReferenceEquals(this.OriginField, value) != true)) {
                    this.OriginField = value;
                    this.RaisePropertyChanged("Origin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XMLDetail {
            get {
                return this.XMLDetailField;
            }
            set {
                if ((object.ReferenceEquals(this.XMLDetailField, value) != true)) {
                    this.XMLDetailField = value;
                    this.RaisePropertyChanged("XMLDetail");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StatusFilter", Namespace="http://sdl.com/trisoft/2012/06/WebServices/Contracts/Enumerations/API25/")]
    public enum StatusFilter : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ISHReleasedStates = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ISHReleasedOrDraftStates = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ISHOutOfDateOrReleasedStates = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ISHNoStatusFilter = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseFolder", Namespace="http://sdl.com/trisoft/2012/06/WebServices/Contracts/Enumerations/API25/")]
    public enum BaseFolder : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Data = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        System = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Favorites = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EditorTemplate = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LinkType", Namespace="http://sdl.com/trisoft/2012/06/WebServices/Contracts/Enumerations/API25/")]
    public enum LinkType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ContentLink = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HyperLink = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        All = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/", ConfigurationName="DocObj25ServiceReference.DocumentObj")]
    public interface DocumentObj {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/DocumentObj/GetMetadata" +
            "ByIshLngRef", ReplyAction="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/DocumentObj/GetMetadata" +
            "ByIshLngRefResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EdwardsApp1.DocObj25ServiceReference.InfoShareFault), Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/DocumentObj/GetMetadata" +
            "ByIshLngRefInfoShareFault", Name="InfoShareFault", Namespace="http://sdl.com/trisoft/2012/06/WebServices/Contracts/Faults/API25/")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="xmlObjectList")]
        string GetMetadataByIshLngRef(long lngRef, string xmlRequestedMetadata);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/DocumentObj/GetMetadata" +
            "", ReplyAction="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/DocumentObj/GetMetadata" +
            "Response")]
        [System.ServiceModel.FaultContractAttribute(typeof(EdwardsApp1.DocObj25ServiceReference.InfoShareFault), Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/DocumentObj/GetMetadata" +
            "InfoShareFault", Name="InfoShareFault", Namespace="http://sdl.com/trisoft/2012/06/WebServices/Contracts/Faults/API25/")]
        void GetMetadata(string logicalId, ref string version, out string xmlObjectList, string language, string resolution, string xmlRequestedMetadata);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/DocumentObj/RetrieveMet" +
            "adataByIshLngRefs", ReplyAction="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/DocumentObj/RetrieveMet" +
            "adataByIshLngRefsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EdwardsApp1.DocObj25ServiceReference.InfoShareFault), Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/DocumentObj/RetrieveMet" +
            "adataByIshLngRefsInfoShareFault", Name="InfoShareFault", Namespace="http://sdl.com/trisoft/2012/06/WebServices/Contracts/Faults/API25/")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="xmlObjectList")]
        string RetrieveMetadataByIshLngRefs(long[] lngRefs, string xmlRequestedMetadata);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/DocumentObj/RetrieveVer" +
            "sionMetadata", ReplyAction="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/DocumentObj/RetrieveVer" +
            "sionMetadataResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EdwardsApp1.DocObj25ServiceReference.InfoShareFault), Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/DocumentObj/RetrieveVer" +
            "sionMetadataInfoShareFault", Name="InfoShareFault", Namespace="http://sdl.com/trisoft/2012/06/WebServices/Contracts/Faults/API25/")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="xmlObjectList")]
        string RetrieveVersionMetadata(string[] logicalIds, string version, string xmlRequestedMetadata);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/DocumentObj/GetDataObje" +
            "ctInfoByIshLngRef", ReplyAction="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/DocumentObj/GetDataObje" +
            "ctInfoByIshLngRefResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EdwardsApp1.DocObj25ServiceReference.InfoShareFault), Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/DocumentObj/GetDataObje" +
            "ctInfoByIshLngRefInfoShareFault", Name="InfoShareFault", Namespace="http://sdl.com/trisoft/2012/06/WebServices/Contracts/Faults/API25/")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="xmlIshDataObjects")]
        string GetDataObjectInfoByIshLngRef(long lngRef);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/DocumentObj/RetrieveDat" +
            "aObjectInfoByIshLngRefs", ReplyAction="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/DocumentObj/RetrieveDat" +
            "aObjectInfoByIshLngRefsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EdwardsApp1.DocObj25ServiceReference.InfoShareFault), Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/DocumentObj/RetrieveDat" +
            "aObjectInfoByIshLngRefsInfoShareFault", Name="InfoShareFault", Namespace="http://sdl.com/trisoft/2012/06/WebServices/Contracts/Faults/API25/")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="xmlIshDataObjects")]
        string RetrieveDataObjectInfoByIshLngRefs(long[] lngRefs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/DocumentObj/RetrieveObj" +
            "ects", ReplyAction="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/DocumentObj/RetrieveObj" +
            "ectsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EdwardsApp1.DocObj25ServiceReference.InfoShareFault), Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/DocumentObj/RetrieveObj" +
            "ectsInfoShareFault", Name="InfoShareFault", Namespace="http://sdl.com/trisoft/2012/06/WebServices/Contracts/Faults/API25/")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="xmlObjectList")]
        string RetrieveObjects(string[] logicalIds, EdwardsApp1.DocObj25ServiceReference.StatusFilter statusFilter, string xmlMetadataFilter, string xmlProductDefinition, string xmlRequestedMetadata);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/DocumentObj/RetrieveObj" +
            "ectsByIshLngRefs", ReplyAction="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/DocumentObj/RetrieveObj" +
            "ectsByIshLngRefsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EdwardsApp1.DocObj25ServiceReference.InfoShareFault), Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/DocumentObj/RetrieveObj" +
            "ectsByIshLngRefsInfoShareFault", Name="InfoShareFault", Namespace="http://sdl.com/trisoft/2012/06/WebServices/Contracts/Faults/API25/")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="xmlObjectList")]
        string RetrieveObjectsByIshLngRefs(long[] lngRefs, string xmlProductDefinition, string xmlRequestedMetadata);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/DocumentObj/RetrieveObj" +
            "ectsByRevisionIds", ReplyAction="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/DocumentObj/RetrieveObj" +
            "ectsByRevisionIdsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EdwardsApp1.DocObj25ServiceReference.InfoShareFault), Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/DocumentObj/RetrieveObj" +
            "ectsByRevisionIdsInfoShareFault", Name="InfoShareFault", Namespace="http://sdl.com/trisoft/2012/06/WebServices/Contracts/Faults/API25/")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="xmlObjectList")]
        string RetrieveObjectsByRevisionIds(string[] revisionIds, string xmlProductDefinition, string xmlRequestedMetadata);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/DocumentObj/RetrieveRev" +
            "isionInfoByIshLngRefs", ReplyAction="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/DocumentObj/RetrieveRev" +
            "isionInfoByIshLngRefsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EdwardsApp1.DocObj25ServiceReference.InfoShareFault), Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/DocumentObj/RetrieveRev" +
            "isionInfoByIshLngRefsInfoShareFault", Name="InfoShareFault", Namespace="http://sdl.com/trisoft/2012/06/WebServices/Contracts/Faults/API25/")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="xmlObjectList")]
        string RetrieveRevisionInfoByIshLngRefs(long[] lngRefs, string xmlRequestedMetadata);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/DocumentObj/FolderLocat" +
            "ions", ReplyAction="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/DocumentObj/FolderLocat" +
            "ionsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EdwardsApp1.DocObj25ServiceReference.InfoShareFault), Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/DocumentObj/FolderLocat" +
            "ionsInfoShareFault", Name="InfoShareFault", Namespace="http://sdl.com/trisoft/2012/06/WebServices/Contracts/Faults/API25/")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="xmlObjLocationList")]
        string FolderLocations(string[] logicalIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/DocumentObj/Find", ReplyAction="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/DocumentObj/FindRespons" +
            "e")]
        [System.ServiceModel.FaultContractAttribute(typeof(EdwardsApp1.DocObj25ServiceReference.InfoShareFault), Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/DocumentObj/FindInfoSha" +
            "reFault", Name="InfoShareFault", Namespace="http://sdl.com/trisoft/2012/06/WebServices/Contracts/Faults/API25/")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="xmlObjectList")]
        string Find(string ishTypeFilter, EdwardsApp1.DocObj25ServiceReference.StatusFilter statusFilter, string xmlMetadataFilter, string xmlRequestedMetadata);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/DocumentObj/RetrieveMet" +
            "adata", ReplyAction="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/DocumentObj/RetrieveMet" +
            "adataResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EdwardsApp1.DocObj25ServiceReference.InfoShareFault), Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/DocumentObj/RetrieveMet" +
            "adataInfoShareFault", Name="InfoShareFault", Namespace="http://sdl.com/trisoft/2012/06/WebServices/Contracts/Faults/API25/")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="xmlObjectList")]
        string RetrieveMetadata(string[] logicalIds, EdwardsApp1.DocObj25ServiceReference.StatusFilter statusFilter, string xmlMetadataFilter, string xmlRequestedMetadata);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/DocumentObj/RetrieveLan" +
            "guageMetadata", ReplyAction="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/DocumentObj/RetrieveLan" +
            "guageMetadataResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EdwardsApp1.DocObj25ServiceReference.InfoShareFault), Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/DocumentObj/RetrieveLan" +
            "guageMetadataInfoShareFault", Name="InfoShareFault", Namespace="http://sdl.com/trisoft/2012/06/WebServices/Contracts/Faults/API25/")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="xmlObjectList")]
        string RetrieveLanguageMetadata(string[] logicalIds, string version, string[] languages, string[] resolutions, EdwardsApp1.DocObj25ServiceReference.StatusFilter statusFilter, string xmlRequestedMetadata);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/DocumentObj/FolderLocat" +
            "ion", ReplyAction="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/DocumentObj/FolderLocat" +
            "ionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EdwardsApp1.DocObj25ServiceReference.InfoShareFault), Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/DocumentObj/FolderLocat" +
            "ionInfoShareFault", Name="InfoShareFault", Namespace="http://sdl.com/trisoft/2012/06/WebServices/Contracts/Faults/API25/")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="baseFolder")]
        EdwardsApp1.DocObj25ServiceReference.BaseFolder FolderLocation(out string[] folderPath, out long[] folderRefs, string logicalId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/DocumentObj/ContainingL" +
            "ogicalId", ReplyAction="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/DocumentObj/ContainingL" +
            "ogicalIdResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EdwardsApp1.DocObj25ServiceReference.InfoShareFault), Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/DocumentObj/ContainingL" +
            "ogicalIdInfoShareFault", Name="InfoShareFault", Namespace="http://sdl.com/trisoft/2012/06/WebServices/Contracts/Faults/API25/")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="xmlObjectList")]
        string ContainingLogicalId(string logicalId, EdwardsApp1.DocObj25ServiceReference.LinkType linkType, string ishTypeFilter, EdwardsApp1.DocObj25ServiceReference.StatusFilter statusFilter, string xmlMetadataFilter, string xmlRequestedMetadata);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/DocumentObj/GetParentsB" +
            "yIshLngRef", ReplyAction="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/DocumentObj/GetParentsB" +
            "yIshLngRefResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EdwardsApp1.DocObj25ServiceReference.InfoShareFault), Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/DocumentObj/GetParentsB" +
            "yIshLngRefInfoShareFault", Name="InfoShareFault", Namespace="http://sdl.com/trisoft/2012/06/WebServices/Contracts/Faults/API25/")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="xmlObjectList")]
        string GetParentsByIshLngRef(long lngRef, EdwardsApp1.DocObj25ServiceReference.LinkType linkType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/DocumentObj/ContainingC" +
            "ondition", ReplyAction="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/DocumentObj/ContainingC" +
            "onditionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EdwardsApp1.DocObj25ServiceReference.InfoShareFault), Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/DocumentObj/ContainingC" +
            "onditionInfoShareFault", Name="InfoShareFault", Namespace="http://sdl.com/trisoft/2012/06/WebServices/Contracts/Faults/API25/")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="xmlObjectList")]
        string ContainingCondition(string conditionName, string conditionValue, string ishTypeFilter, EdwardsApp1.DocObj25ServiceReference.StatusFilter statusFilter, string xmlMetadataFilter, string xmlRequestedMetadata);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/DocumentObj/ContainingV" +
            "ariable", ReplyAction="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/DocumentObj/ContainingV" +
            "ariableResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EdwardsApp1.DocObj25ServiceReference.InfoShareFault), Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/DocumentObj/ContainingV" +
            "ariableInfoShareFault", Name="InfoShareFault", Namespace="http://sdl.com/trisoft/2012/06/WebServices/Contracts/Faults/API25/")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="xmlObjectList")]
        string ContainingVariable(string variable, string ishTypeFilter, EdwardsApp1.DocObj25ServiceReference.StatusFilter statusFilter, string xmlMetadataFilter, string xmlRequestedMetadata);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/DocumentObj/GetParents", ReplyAction="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/DocumentObj/GetParentsR" +
            "esponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EdwardsApp1.DocObj25ServiceReference.InfoShareFault), Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/DocumentObj/GetParentsI" +
            "nfoShareFault", Name="InfoShareFault", Namespace="http://sdl.com/trisoft/2012/06/WebServices/Contracts/Faults/API25/")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="xmlObjectList")]
        string GetParents(string logicalId, EdwardsApp1.DocObj25ServiceReference.LinkType linkType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/DocumentObj/GetChildren" +
            "", ReplyAction="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/DocumentObj/GetChildren" +
            "Response")]
        [System.ServiceModel.FaultContractAttribute(typeof(EdwardsApp1.DocObj25ServiceReference.InfoShareFault), Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/DocumentObj/GetChildren" +
            "InfoShareFault", Name="InfoShareFault", Namespace="http://sdl.com/trisoft/2012/06/WebServices/Contracts/Faults/API25/")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="logicalIds")]
        string[] GetChildren(long lngRef, EdwardsApp1.DocObj25ServiceReference.LinkType linkType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/DocumentObj/GetPossible" +
            "TargetStatuses", ReplyAction="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/DocumentObj/GetPossible" +
            "TargetStatusesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EdwardsApp1.DocObj25ServiceReference.InfoShareFault), Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/DocumentObj/GetPossible" +
            "TargetStatusesInfoShareFault", Name="InfoShareFault", Namespace="http://sdl.com/trisoft/2012/06/WebServices/Contracts/Faults/API25/")]
        void GetPossibleTargetStatuses(string logicalId, ref string version, out string xmlLovValueList, string language, string resolution);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/DocumentObj/GetPossible" +
            "TargetStatusesByIshLngRef", ReplyAction="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/DocumentObj/GetPossible" +
            "TargetStatusesByIshLngRefResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EdwardsApp1.DocObj25ServiceReference.InfoShareFault), Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/DocumentObj/GetPossible" +
            "TargetStatusesByIshLngRefInfoShareFault", Name="InfoShareFault", Namespace="http://sdl.com/trisoft/2012/06/WebServices/Contracts/Faults/API25/")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="xmlLovValueList")]
        string GetPossibleTargetStatusesByIshLngRef(long lngRef);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/DocumentObj/ReuseStarte" +
            "dOn", ReplyAction="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/DocumentObj/ReuseStarte" +
            "dOnResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EdwardsApp1.DocObj25ServiceReference.InfoShareFault), Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/DocumentObj/ReuseStarte" +
            "dOnInfoShareFault", Name="InfoShareFault", Namespace="http://sdl.com/trisoft/2012/06/WebServices/Contracts/Faults/API25/")]
        void ReuseStartedOn(string logicalId, string versionNumber, string[] reusableObjectLogicalIds);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DocumentObjChannel : EdwardsApp1.DocObj25ServiceReference.DocumentObj, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DocumentObjClient : System.ServiceModel.ClientBase<EdwardsApp1.DocObj25ServiceReference.DocumentObj>, EdwardsApp1.DocObj25ServiceReference.DocumentObj {
        
        public DocumentObjClient() {
        }
        
        public DocumentObjClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DocumentObjClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DocumentObjClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DocumentObjClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetMetadataByIshLngRef(long lngRef, string xmlRequestedMetadata) {
            return base.Channel.GetMetadataByIshLngRef(lngRef, xmlRequestedMetadata);
        }
        
        public void GetMetadata(string logicalId, ref string version, out string xmlObjectList, string language, string resolution, string xmlRequestedMetadata) {
            base.Channel.GetMetadata(logicalId, ref version, out xmlObjectList, language, resolution, xmlRequestedMetadata);
        }
        
        public string RetrieveMetadataByIshLngRefs(long[] lngRefs, string xmlRequestedMetadata) {
            return base.Channel.RetrieveMetadataByIshLngRefs(lngRefs, xmlRequestedMetadata);
        }
        
        public string RetrieveVersionMetadata(string[] logicalIds, string version, string xmlRequestedMetadata) {
            return base.Channel.RetrieveVersionMetadata(logicalIds, version, xmlRequestedMetadata);
        }
        
        public string GetDataObjectInfoByIshLngRef(long lngRef) {
            return base.Channel.GetDataObjectInfoByIshLngRef(lngRef);
        }
        
        public string RetrieveDataObjectInfoByIshLngRefs(long[] lngRefs) {
            return base.Channel.RetrieveDataObjectInfoByIshLngRefs(lngRefs);
        }
        
        public string RetrieveObjects(string[] logicalIds, EdwardsApp1.DocObj25ServiceReference.StatusFilter statusFilter, string xmlMetadataFilter, string xmlProductDefinition, string xmlRequestedMetadata) {
            return base.Channel.RetrieveObjects(logicalIds, statusFilter, xmlMetadataFilter, xmlProductDefinition, xmlRequestedMetadata);
        }
        
        public string RetrieveObjectsByIshLngRefs(long[] lngRefs, string xmlProductDefinition, string xmlRequestedMetadata) {
            return base.Channel.RetrieveObjectsByIshLngRefs(lngRefs, xmlProductDefinition, xmlRequestedMetadata);
        }
        
        public string RetrieveObjectsByRevisionIds(string[] revisionIds, string xmlProductDefinition, string xmlRequestedMetadata) {
            return base.Channel.RetrieveObjectsByRevisionIds(revisionIds, xmlProductDefinition, xmlRequestedMetadata);
        }
        
        public string RetrieveRevisionInfoByIshLngRefs(long[] lngRefs, string xmlRequestedMetadata) {
            return base.Channel.RetrieveRevisionInfoByIshLngRefs(lngRefs, xmlRequestedMetadata);
        }
        
        public string FolderLocations(string[] logicalIds) {
            return base.Channel.FolderLocations(logicalIds);
        }
        
        public string Find(string ishTypeFilter, EdwardsApp1.DocObj25ServiceReference.StatusFilter statusFilter, string xmlMetadataFilter, string xmlRequestedMetadata) {
            return base.Channel.Find(ishTypeFilter, statusFilter, xmlMetadataFilter, xmlRequestedMetadata);
        }
        
        public string RetrieveMetadata(string[] logicalIds, EdwardsApp1.DocObj25ServiceReference.StatusFilter statusFilter, string xmlMetadataFilter, string xmlRequestedMetadata) {
            return base.Channel.RetrieveMetadata(logicalIds, statusFilter, xmlMetadataFilter, xmlRequestedMetadata);
        }
        
        public string RetrieveLanguageMetadata(string[] logicalIds, string version, string[] languages, string[] resolutions, EdwardsApp1.DocObj25ServiceReference.StatusFilter statusFilter, string xmlRequestedMetadata) {
            return base.Channel.RetrieveLanguageMetadata(logicalIds, version, languages, resolutions, statusFilter, xmlRequestedMetadata);
        }
        
        public EdwardsApp1.DocObj25ServiceReference.BaseFolder FolderLocation(out string[] folderPath, out long[] folderRefs, string logicalId) {
            return base.Channel.FolderLocation(out folderPath, out folderRefs, logicalId);
        }
        
        public string ContainingLogicalId(string logicalId, EdwardsApp1.DocObj25ServiceReference.LinkType linkType, string ishTypeFilter, EdwardsApp1.DocObj25ServiceReference.StatusFilter statusFilter, string xmlMetadataFilter, string xmlRequestedMetadata) {
            return base.Channel.ContainingLogicalId(logicalId, linkType, ishTypeFilter, statusFilter, xmlMetadataFilter, xmlRequestedMetadata);
        }
        
        public string GetParentsByIshLngRef(long lngRef, EdwardsApp1.DocObj25ServiceReference.LinkType linkType) {
            return base.Channel.GetParentsByIshLngRef(lngRef, linkType);
        }
        
        public string ContainingCondition(string conditionName, string conditionValue, string ishTypeFilter, EdwardsApp1.DocObj25ServiceReference.StatusFilter statusFilter, string xmlMetadataFilter, string xmlRequestedMetadata) {
            return base.Channel.ContainingCondition(conditionName, conditionValue, ishTypeFilter, statusFilter, xmlMetadataFilter, xmlRequestedMetadata);
        }
        
        public string ContainingVariable(string variable, string ishTypeFilter, EdwardsApp1.DocObj25ServiceReference.StatusFilter statusFilter, string xmlMetadataFilter, string xmlRequestedMetadata) {
            return base.Channel.ContainingVariable(variable, ishTypeFilter, statusFilter, xmlMetadataFilter, xmlRequestedMetadata);
        }
        
        public string GetParents(string logicalId, EdwardsApp1.DocObj25ServiceReference.LinkType linkType) {
            return base.Channel.GetParents(logicalId, linkType);
        }
        
        public string[] GetChildren(long lngRef, EdwardsApp1.DocObj25ServiceReference.LinkType linkType) {
            return base.Channel.GetChildren(lngRef, linkType);
        }
        
        public void GetPossibleTargetStatuses(string logicalId, ref string version, out string xmlLovValueList, string language, string resolution) {
            base.Channel.GetPossibleTargetStatuses(logicalId, ref version, out xmlLovValueList, language, resolution);
        }
        
        public string GetPossibleTargetStatusesByIshLngRef(long lngRef) {
            return base.Channel.GetPossibleTargetStatusesByIshLngRef(lngRef);
        }
        
        public void ReuseStartedOn(string logicalId, string versionNumber, string[] reusableObjectLogicalIds) {
            base.Channel.ReuseStartedOn(logicalId, versionNumber, reusableObjectLogicalIds);
        }
    }
}
